apiVersion: skaffold/v2alpha3
kind: Config
build:
    local:
        push: false
    artifacts:
        - image: rfiguerasdegea/multi-client
          context: client
          docker:
            dockerfile: Dockerfile.dev
          sync:
            infer:
            - '**/*.js'
            - '**/*.css'
            - '**/*.html'
        - image: rfiguerasdegea/multi-server
          context: server
          docker:
            dockerfile: Dockerfile.dev
          sync:
            infer:
            - '**/*.js'
        - image: rfiguerasdegea/multi-worker
          context: worker
          docker:
            dockerfile: Dockerfile.dev
          sync:
            infer:
            - '**/*.js'
         
deploy:
    kubectl:
        manifests:
            - k8s/client-deployment.yaml