apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
#        server: https://acme-staging-v02.api.letsencrypt.org/directory
        email: rfiguerasdegea@outlook.com
        privateKeySecretRef:
            name: letsencrypt-prod
        solvers:
        - selector: {}
            http01:
                ingress:
                    class: nginx